from __future__ import annotations

from io import StringIO
from typing import List, Dict
import pandas as pd


class HTMLTableParser:
    """
    Production wrapper around pandas.read_html() to parse raw HTML table elements,
    expand spanned rows (rowspan), and flatten MultiIndex header rows (colspan).
    """

    def __init__(
        self,
        forward_fill: bool = True,
        drop_empty_rows: bool = True,
        drop_empty_cols: bool = True,
        flatten_headers: bool = True,
    ):
        self.forward_fill = forward_fill
        self.drop_empty_rows = drop_empty_rows
        self.drop_empty_cols = drop_empty_cols
        self.flatten_headers = flatten_headers

    def parse_html(self, html: str) -> List[pd.DataFrame]:
        """
        Parses all table elements in raw HTML string into clean DataFrames.
        """
        return self._parse_tables(html)

    def parse_table(self, table_element) -> pd.DataFrame:
        """
        Parses a single BeautifulSoup table tag into a cleaned DataFrame.
        """
        html = str(table_element)
        parsed = self._parse_tables(html)
        return parsed[0] if parsed else pd.DataFrame()

    def parse_to_records(self, html: str) -> List[List[Dict]]:
        """
        Helper returning a list of dictionaries per row for all parsed tables.
        """
        dfs = self._parse_tables(html)
        return [df.to_dict(orient="records") for df in dfs]

    def _parse_tables(self, html: str) -> List[pd.DataFrame]:
        try:
            dfs = pd.read_html(StringIO(html))
        except ValueError:
            # Raised by pandas if no table element is found
            return []
        except Exception:
            return []

        cleaned = []
        for df in dfs:
            df = self._clean_dataframe(df)
            cleaned.append(df)
        return cleaned

    def _clean_dataframe(self, df: pd.DataFrame) -> pd.DataFrame:
        # 1. Flatten MultiIndex columns
        if self.flatten_headers and isinstance(df.columns, pd.MultiIndex):
            new_columns = []
            for col in df.columns:
                parts = []
                for x in col:
                    val = str(x).strip()
                    # Skip autogenerated or empty indexes
                    if pd.notna(x) and val and "Unnamed" not in val:
                        parts.append(val)
                new_columns.append(" > ".join(parts) if parts else "column")
            df.columns = new_columns
        else:
            df.columns = [str(c).replace("\n", " ").strip() for c in df.columns]

        # 2. Normalize and clean whitespace in cell values
        df = df.map(
            lambda x: str(x).replace("\xa0", " ").strip()
            if pd.notna(x)
            else None
        )

        # 3. Forward fill rowspan cells
        if self.forward_fill:
            df = df.ffill()

        # 4. Remove empty rows
        if self.drop_empty_rows:
            df = df.dropna(how="all")

        # 5. Remove empty columns
        if self.drop_empty_cols:
            df = df.dropna(axis=1, how="all")

        return df.reset_index(drop=True)

    @staticmethod
    def dataframe_to_markdown(df: pd.DataFrame) -> str:
        """
        Returns a formatted markdown table.
        """
        return df.to_markdown(index=False)

    @staticmethod
    def dataframe_to_records(df: pd.DataFrame) -> List[Dict]:
        """
        Converts DataFrame rows to key-value record dictionaries.
        """
        return df.to_dict(orient="records")
