from sqlalchemy.ext.asyncio import AsyncSession
from typing import Sequence
from app.auth.models import User, ApiKey
from app.auth.schemas import UserCreate, LoginRequest
from app.auth.repository import UserRepository, ApiKeyRepository
from app.auth.exceptions import (
    UserAlreadyExistsException,
    InvalidCredentialsException,
    CredentialsException,
    UserNotFoundException
)
from app.auth.security import (
    hash_password,
    verify_password,
    generate_api_key,
    hash_api_key
)

class AuthService:
    @staticmethod
    async def register_user(db: AsyncSession, user_create: UserCreate) -> User:
        """
        Registers a new user record.
        """
        if await UserRepository.get_by_email(db, user_create.email):
            raise UserAlreadyExistsException("User with this email already exists")

        if await UserRepository.get_by_user_id(db, user_create.user_id):
            raise UserAlreadyExistsException("User ID is already taken")

        hashed_password = await hash_password(user_create.password)

        user = User(
            name=user_create.name,
            user_id=user_create.user_id,
            email=user_create.email,
            password_hash=hashed_password,
            role=user_create.role or "user"
        )
        return await UserRepository.create(db, user)

    @staticmethod
    async def authenticate_user(db: AsyncSession, login_req: LoginRequest) -> User:
        """
        Verifies login credentials and returns the User object.
        """
        user = await UserRepository.get_by_email(db, login_req.email)
        if not user:
            raise InvalidCredentialsException()

        if not await verify_password(login_req.password, user.password_hash):
            raise InvalidCredentialsException()

        return user

    @staticmethod
    async def create_api_key(db: AsyncSession, user_id: int, name: str) -> dict:
        """
        Generates a secure API key, stores its SHA-256 hash, and returns plain key details.
        """
        raw_key, prefix = await generate_api_key()
        key_hash = await hash_api_key(raw_key)

        api_key = ApiKey(
            name=name,
            prefix=prefix,
            key_hash=key_hash,
            user_id=user_id
        )
        api_key = await ApiKeyRepository.create(db, api_key)

        return {
            "id": api_key.id,
            "name": api_key.name,
            "prefix": api_key.prefix,
            "is_active": api_key.is_active,
            "plain_key": raw_key
        }

    @staticmethod
    async def validate_api_key(db: AsyncSession, plain_key: str) -> User:
        """
        Hashes the plaintext API key and returns the owner User model if active.
        """
        key_hash = await hash_api_key(plain_key)
        api_key = await ApiKeyRepository.get_by_hash(db, key_hash)
        if not api_key or not api_key.is_active:
            raise CredentialsException(detail="Invalid or inactive API Key")
        return api_key.user

    @staticmethod
    async def list_api_keys(db: AsyncSession, user_id: int) -> Sequence[ApiKey]:
        """
        Lists all API keys generated by a specific user.
        """
        return await ApiKeyRepository.get_by_user_id(db, user_id)

    @staticmethod
    async def revoke_api_key(db: AsyncSession, user_id: int, key_id: int) -> None:
        """
        Revokes (deletes) a specific API key belonging to a user.
        """
        api_key = await ApiKeyRepository.get_by_id(db, key_id)
        if not api_key or api_key.user_id != user_id:
            raise UserNotFoundException(detail="API Key not found or does not belong to this user")
        await ApiKeyRepository.delete(db, api_key)

    @staticmethod
    async def update_user_role(db: AsyncSession, username: str, new_role: str) -> User:
        """
        Updates the role for a specific username user.
        """
        user = await UserRepository.get_by_user_id(db, username)
        if not user:
            raise UserNotFoundException(detail="User not found")
        user.role = new_role
        await db.commit()
        await db.refresh(user)
        return user

